twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_3_horizontal_layout.html.twig'
    globals:
        locales: '%languages'
        themes: '%themes'
        default_theme: '%default_theme'
